export * from './LogoPage/LogoPage';
export * from './login/loginpage';
export * from './feed';
export * from './cadastro/signup/SignupPage';
export * from './cadastro/endereco/CadastroEndereco';
export * from './perfil/perfil/Perfil';
export * from './perfil/editar-cadastro/EditarCadastro';
export * from './perfil/editar-endereco/EditarEndereco';
export * from './search/Busca'
export * from './restaurante/restaurante/Restaurante';
export * from './restaurante/confirmacao/Confirmacao';
export * from './carrinho/cart/Cart';
export * from './carrinho/carrinho';
export * from './pedido-andamento';
